module.exports = {
  email: "portier.vin@gmail.com",
  socialMedia: [
    { name: "Github", url: "https://github.com/vincentportier" },
    { name: "LinkedIn", url: "https://linkedin.com/in/portiervincent" },
    { name: "CodeWar", url: "https://www.codewars.com/users/vincentportier" },
    { name: "Instagram", url: "https://www.instagram.com/letsgosmwhr/" },
  ],
  navLinks: [
    { name: "About", url: "/#about" },
    {
      name: "Projects",
      url: "/#projects",
    },
    { name: "Contact", url: "/#contact" },
  ],
  srConfig: (delay = 500, viewFactor = 0.25) => ({
    delay,
    distance: "0px",
    duration: 600,
    easing: "cubic-bezier(0.5, 0, 0, 1)",
    interval: 0,
    opacity: 0,
    origin: "bottom",
    rotate: {
      x: 0,
      y: 0,
      z: 0,
    },
    scale: 0.9,
    cleanup: false,
    desktop: true,
    mobile: true,
    reset: false,
    useDelay: "always",
    viewFactor,
  }),
  skills: [
    "JavaScript ES6",
    "React",
    "HTML5",
    "CSS/Sass",
    "React Redux",
    "React Hooks",
    "Gatsby",
    "Firebase",
    "Git",
    "Netlify",
    "Styled components",
    "Material-UI",
  ],
  projects: [
    {
      title: "vportier.com",
      description:
        "First iteration of my personal portfolio. I have built it with Gatsby and React and it is hosted with Netlify. Gatsby ships with some great features like a built-in Router or image optimisation tools which convinced me to use it for my website. I used Hooks and Context to manage dark mode and scrollReveal for some of the animations. I plan to learn more about GraphQL to query my website and dynamically render content uploaded in Markdown as the site grows bigger.",

      technologies: [
        "Gatsby",
        "JavaScript",
        "React",
        "Styled Components",
        "Hooks",
        "Context",
      ],
      external: "https://vportier.com",
      github: "https://github.com/vincentportier/portfolio",
      image: "/og.png",
    },
    {
      title: "Toudo",
      description:
        "Toudo is a web app that helps you organize your life. You can create tasks, schedule, prioritise, sort, file and comment on them. Toudo manages authentication and saves your tasks in Firebase. Toudo uses custom hooks to make firebase calls and set the context of the app with your tasks and projects.",
      technologies: [
        "React",
        "Firebase",
        "Hooks",
        "Context",
        "HTML",
        "CSS",
        "React Router",
      ],
      external: "https://toudo.netlify.app",
      github: "https://github.com/vincentportier/toudo",
      image: "/toudo.png",
    },
    {
      title: "The Resistance: Avalon",
      description:
        "This web app is an adaptation of the game The Resistance: Avalon. The game logic is written in JavaScript. The Javascript is used to update the game parameters based on the number of players, to randomly assign a role to each player, to dynamically update the DOM and to check for end-game conditions.",
      technologies: ["JavaScript", "React", "React Router", "HTML", "CSS"],
      external: "https://avalon-game.netlify.app",
      github: "https://github.com/vincentportier/avalon-game",
      image: "/avalon.png",
    },
    {
      title: "FreeCodeCamp certification projects",
      description:
        "Each FreeCodeCamp certification requires to complete 5 projects to finalise the course. I have built 15 projects, including static webpages, a random quote generator, a pomodoro clock, a calculator, a markdown text editor and a drum-machine. I have centralised my last 5 projects in a GitHub repository where you'll find links to the hosted projects.",
      technologies: ["JavaScript", "React", "Redux", "HTML", "CSS"],
      github: "https://github.com/vincentportier/FreeCodeCamp",
      image: "/fcc.png",
    },
  ],
}
