module.exports = {
  email: "portier.vin@gmail.com",
  socialMedia: [
    { name: "Github", url: "https://github.com/vincentportier" },
    { name: "LinkedIn", url: "https://linkedin.com/in/portiervincent" },
    { name: "CodeWar", url: "https://www.codewars.com/users/vincentportier" },
    { name: "Instagram", url: "https://www.instagram.com/letsgosmwhr/" },
  ],
  navLinks: [
    { name: "About", url: "/#about" },
    {
      name: "Projects",
      url: "/#projects",
    },
    { name: "Contact", url: "/#contact" },
  ],
  srConfig: (delay = 500, viewFactor = 0.25) => ({
    delay,
    distance: "0px",
    duration: 600,
    easing: "cubic-bezier(0.5, 0, 0, 1)",
    interval: 0,
    opacity: 0,
    origin: "bottom",
    rotate: {
      x: 0,
      y: 0,
      z: 0,
    },
    scale: 0.9,
    cleanup: false,
    desktop: true,
    mobile: true,
    reset: false,
    useDelay: "always",
    viewFactor,
  }),
  skills: [
    "JavaScript ES6",
    "React",
    "HTML5",
    "CSS/Sass",
    "React Redux",
    "React Hooks",
    "Gatsby",
    "Firebase",
    "Git",
    "Netlify",
    "Styled components",
    "Material-UI",
  ],
}
